"""empty message

Revision ID: 083e3a346aa2
Revises: ed589e68fe03
Create Date: 2023-07-17 15:27:40.253843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '083e3a346aa2'
down_revision = 'ed589e68fe03'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
