"""empty message

Revision ID: bda2a5d79f69
Revises: d6f225c6e970
Create Date: 2023-07-14 11:21:52.016567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bda2a5d79f69'
down_revision = 'd6f225c6e970'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'create_time')
    op.drop_column('reminders', 'create_time')
    op.add_column('reminders', sa.Column('departure_date', sa.DateTime(), nullable=False))
    op.add_column('reminders', sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()')))
    op.add_column('users', sa.Column('username', sa.String(), nullable=False))
    op.add_column('users', sa.Column('create_time', sa.DateTime(),  server_default=sa.text('now()')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username')
    op.drop_column('reminders', 'departure_date')
    # ### end Alembic commands ###
